### ISSUE TITLE
Нет лицензии

### ISSUE THREAD

**Issue by vanaigr** [Jsgdibd148/MyTestSite#1]
А попоч на сайте написано "© Все права защищены" если в репозитории нет лицензии ?

Или Вы просто выступаете за защиту прав, а надпись на сайте показывает ваши намерения ?

**Comment by Jsgdibd148** [comment]
@vanaigr

**Comment by vanaigr** [comment]
> @vanaigr

Удаляй при мне

**Comment by Jsgdibd148** [comment]
Удалить моё сообщение?

**Comment by Jsgdibd148** [comment]
> > @vanaigr
> 
> Удаляй при мне

Удалил

**Comment by vanaigr** [comment]
> > > @vanaigr
> > 
> > 
> > Удаляй при мне
> 
> Удалил

Молодец, это тоже можушь удалить

**Comment by vanaigr** [comment]
Ну так можешь удалить? Или удалялка сломалась?

**Comment by Jsgdibd148** [comment]
Как просил :)

**Comment by vanaigr** [comment]
Я разве просил? Я тут не вижу чтобы я просил удалять мой коммент...

**Comment by Jsgdibd148** [comment]
Конечно, не видишь. По твоей просьбе он был удалён 🙄

**Comment by vanaigr** [comment]
> Конечно, не видишь. По твоей просьбе он был удалён 🙄

Лжешь 😶‍🌫️
докажи...

**Comment by Jsgdibd148** [comment]
Ты первый.

**Comment by vanaigr** [comment]
> Ты первый.

так я первый вопрос задал. И ты меня ничего не просил

**Comment by Jsgdibd148** [comment]
Я обладаю силой закрыть этот issues, которая и не снилась моему отцу. Так что давай - доказывай. 😎

**Comment by vanaigr** [comment]
Вкурсе, что я тоже могу

**Comment by Jsgdibd148** [comment]
![2](https://github.com/user-attachments/assets/87833285-c446-4b07-be5d-488d1a5d1d59)

**Comment by vanaigr** [comment]
Ультрамегахарош

**Comment by vanaigr** [comment]
Только  на вопрос ты так и не ответил 😁

**Comment by vanaigr** [comment]
а эту работу тызда?

**Comment by vanaigr** [comment]
@Jsgdibd148 я блефанул в твоём репозирории, сори. Хотел признаться на роджєство 😘
